version: "3.7"

services:
  uptime-heartbeat:
    image: "uptime-heartbeat"
    build:
      context: .
    environment:
      push_url: ""
      push_interval: 55
      cf_access_client_id: 
      cf_access_client_secret: 
    restart: on-failure
